trainingInput:
  scaleTier: CUSTOM
  # Configure a master worker with 4 K80 GPUs
  masterType: n1-standard-32
  masterConfig:
    acceleratorConfig:
      count: 8
      type: NVIDIA_TESLA_K80
  # Configure 9 workers, each with 4 K80 GPUs
  workerCount: 0
  workerType: n1-highcpu-16
  workerConfig:
    acceleratorConfig:
      count: 0
      type: NVIDIA_TESLA_P100
  # Configure 3 parameter servers with no GPUs
  parameterServerCount: 0
  parameterServerType: n1-highmem-8